### ISSUE TITLE
Issue installing cli-premium

### ISSUE THREAD

**Issue by relaypilot** [laravel-shift/cli#13]
When running `composer global require laravel-shift/cli-premium` (or even in a single project), I get the following error:

    Could not find a matching version of package laravel-shift/cli-premium. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).

- Using PHP 8.1 and Laravel 10.10
- Using `"minimum-stability": "dev"`
- I have my `auth.json` set up correctly with the username/password containing a valid UUID license (valid until July 2024).
- I have no issue installing `laravel-shift/cli` in my project or globally.

Did the `cli-premium` path changed recently? It used to work a month ago.

**Comment by relaypilot** [comment]
I needed to update my composer.json with the following bit:

```
"repositories": [
    {
        "type": "composer",
        "url": "https://satis.laravelshift.com"
    }
],
```

**Comment by jasonmccreary** [comment]
Glad you got it. The welcome email (or email I sent to existing license holders) should have noted that addition to `composer.json`. Let me know if not so I can make it easier for future users.

**Comment by Konafets** [comment]
@jasonmccreary I your mail with subject "Introducing the Shift CLI" from 25.09.2023 I can not find any information about adding a repository to `composer.json`. Can you add this to the FAQ at https://laravelshift.com/cli?
