### ISSUE TITLE
Error installing globally

### ISSUE THREAD

**Issue by edalzell** [laravel-shift/cli#3]
<img width="542" alt="CleanShot 2023-09-20 at 14 45 42@2x" src="https://github.com/laravel-shift/cli/assets/6069653/0e7ef43c-c3cb-4a11-a325-79507e052149">

**Comment by jasonmccreary** [comment]
First issue!

This should be fixed. I recently changed the package name from `laravel-shift/shift-cli` to simply `laravel-shift/cli`. However, I did not updated it on Packagist.
