### ISSUE TITLE
List of premium tasks

### ISSUE THREAD

**Issue by relaypilot** [laravel-shift/cli#8]
We have a list of free tasks in the README, which is very useful: 

https://github.com/laravel-shift/cli/blob/e25bca813db7749a53e4aa820190c9a662286624/README.md?plain=1#L49C1-L64C99

Could we also have a list of commands to run for premium tasks?

- Adopt Type Hints
- Remove redundant DocBlock tags
- Format test cases
- Request injection
- Request data access
- View data
- Fluent Responses
- Fluent Routes
- Blade Directives
- env to config
- Class based routes
- Remove Laravel DocBlocks
- Adopt unguarded models
- Adopt stringables
- Adopt attribute accessors/mutators
- Adopt if helpers
- Adopt Laravel type hints

**Comment by jasonmccreary** [comment]
Run: `shift-cli --tasks`
